### ISSUE TITLE
Geneste interactieve elementen

### ISSUE THREAD

**Issue by KrijnHoetmer** [Duneyasaleh/the-startup-responsive-interactieve-website#2]
Als algemene regel: interactieve elementen kun je niet nesten. Hoe maak je deze markup beter? Hint: de - is alleen een icon, en het label zelf is misschien de button.

https://github.com/Duneyasaleh/the-startup-responsive-interactieve-website/blob/450ec4bda507270049beb69be6ac7fc82d5402c4/index.html#L68-L71

**Comment by Duneyasaleh** [comment]
Ik heb nu a link met after
